# From file: config.base.toml
theme = "monokai"

## no support:  https://www.reddit.com/r/HelixEditor/comments/1qic88g/darklight_theme_switching_now_works_with_ghostty/?utm_source=openai
#[theme]
#light="monokai"
#dark="monokai"

[editor]
line-number = "relative"  # 显示相对行号 default: absolute

[editor.auto-save]
focus-lost=true
after-delay.enable=true
after-delay.timeout=1000

[editor.cursor-shape]
insert = "bar"


# From file: vim.keymapping.toml
[keys.normal]
## vim bindings
"," = "@<space>"
x = "delete_char_forward"
V = ["extend_line_below", "select_mode"]
H = "goto_line_start"
0 = "goto_line_start"
"^" = "goto_first_nonwhitespace"
"$" = "goto_line_end"
D = "kill_to_line_end"
G = "goto_last_line"
home = "goto_line_start"
end = "goto_line_end"
Z = {Q = ":quit!", Z = ":write-quit!"}

[keys.normal.d]
d = ["extend_line_below", "delete_selection"]
j = ["extend_line_below", "extend_line_below", "delete_selection"]
k = ["extend_line_above", "extend_line_above", "delete_selection"]
down = ["extend_line_below", "extend_line_below", "delete_selection"]
up = ["extend_line_above", "extend_line_above", "delete_selection"]

[keys.normal.g]
g = "goto_file_start"

[keys.select]
esc = ["collapse_selection", "normal_mode"]
G = "extend_to_last_line"
# 你说的现象是因为我们在 select 模式 用的是 extend_line_*，它只会“扩展”，不会按锚点“缩回”。
# Helix 里有专门的 select_line_above/below，会根据锚点自动扩展或收缩，行为更接近 Vim 的行选择。
j = "select_line_below"
k = "select_line_above"
down = "select_line_below"
up = "select_line_above"

[keys.select.g]
g = "extend_to_file_start"


