[keys.normal]
"," = "@<space>"
x = "delete_char_forward"
V = ["extend_line_below", "select_mode"]
H = "goto_line_start"
0 = "goto_line_start"
"^" = "goto_first_nonwhitespace"
"$" = "goto_line_end"
D = "kill_to_line_end"
G = "goto_last_line"
home = "goto_line_start"
end = "goto_line_end"
Z = {Q = ":quit!", Z = ":write-quit!"}

[keys.normal.d]
d = ["extend_line_below", "delete_selection"]
j = ["extend_line_below", "extend_line_below", "delete_selection"]
k = ["extend_line_above", "extend_line_above", "delete_selection"]

[keys.normal.y]
y = ["extend_line_below", "yank"]
j = ["extend_line_below", "extend_line_below", "yank"]
k = ["extend_line_above", "extend_line_above", "yank"]

[keys.select]
esc = ["collapse_selection", "normal_mode"]
G = "extend_to_last_line"
# Helix 选择模式中 extend_line_*，它只会“扩展”，不会按锚点“缩回”。
# Helix 选择模式中 select_line_above/below，会根据锚点自动扩展或收缩，行为更接近 Vim 的行选择。
j = "select_line_below"
k = "select_line_above"

#Helix 自带gg 以及 num+g
#[keys.select.g]
#g = "extend_to_file_start"
#[keys.normal.g]
#g = "goto_file_start"
